### ISSUE TITLE
Limited Expressions

### ISSUE THREAD

**Issue by barkerja** [themusicman/predicated#4]
Just discovered this library, and really excited by its potential use! However, in some testing I discovered the expressions are very limited. Take the following example:

```elixir
iex(26)> email = "test@user.com"
"test@user.com"

iex(27)> Predicated.Query.new("email == 'test@user.com'")
{:error,
 "expected (, followed by expr, followed by ) or whitespace or nothing, followed by utf8 codepoint in the range \"a\" to \"z\" or in the range \"A\" to \"Z\" or in the range \"0\" to \"9\" or equal to \"_\" or equal to \".\", <snip>"}
 ```

Should a string expression just allow any utf8 string?

```elixir
string_expression =
    ignore(whitespace)
    |> ignore(string("'"))
    |> utf8_string([], min: 1) # Allow any utf8 string
    |> ignore(string("'"))
    |> optional(cast)
    |> reduce({Enum, :join, [""]})
    |> unwrap_and_tag(:string_expression)
```

**Comment by themusicman** [comment]
I pushed up a new version `1.1.2` that should expand the string characters to include all except a single quote. I limited it at the time because I didn't know how to handle the single quote. After seeing your issue and reading through the NimbleParsec source again I noticed this little [gem](https://github.com/dashbitco/nimble_parsec/blob/v1.4.0/lib/nimble_parsec.ex#L1826). Still need to figure out how handle parsing an escaped version of the single quote but it is better than before. :) 

I added a [test](https://github.com/themusicman/predicated/blob/main/test/predicated/query/parser_test.exs#L73) for your sample above.

Thanks for posting the issue. I am pretty excited about what can be done with it too. I just need to find more time to work on it. Let me know if you build anything with it. If it is open source I would love to link to your project in Predicated's README.

**Comment by barkerja** [comment]
Thank you! I'll be digging into this a bit more in the coming weeks. We have been using the wonderful [solid library](https://github.com/edgurgel/solid) to accomplish the same thing, but it comes with a lot of limitations.

Predicated may assist with cleaning up a lot of things for us as well as some increased performance (some quick benchee tests show at least a 3x-4x increase for predicate checks).

If you're curious _how_ we've been using Solid, which is a liquid template library, for predicate checks. We've simply just been wrapping the predicates in a `{% if expression %}true{% else %}false{% end %}` and then coercing the result to a boolean.

**Comment by themusicman** [comment]
Cool. I haven't gotten to the point of doing any performance optimization but not having the overhead of a full template language parser I am sure helps.
